name: Build and Release Extension Charts on Release

on:
  workflow_dispatch:
  release:
    types: [released]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  setup-release-tag:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.determine_tag.outputs.release_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Determine release tag
        id: determine_tag
        run: |
          if [[ "${{ github.event.release.tag_name }}" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            RELEASE_TAG="harvester-${BASH_REMATCH[1]}"
            echo "${RELEASE_TAG}"
            echo "release_tag=${RELEASE_TAG}" >> $GITHUB_OUTPUT
          else
            echo "Error: invalid tag format." && exit 1
          fi
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Check package version
        env:
          TAG_VERSION: ${{ github.event.release.tag_name }}
        run: ./scripts/check-version.sh $TAG_VERSION

  build-extension-charts:
    needs:
      - setup-release-tag
      - check-version
    uses: rancher/dashboard/.github/workflows/build-extension-charts.yml@9bf23dff6650116673346447bcf0b088e0edb27f # creators-pkg-v3.0.12
    permissions:
      contents: write
      pull-requests: write
    with:
      target_branch: gh-pages
      tagged_release: '${{ needs.setup-release-tag.outputs.release_tag }}'
