{{- if .Values.netbird.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.netbird.name }}-config
  namespace: {{ .Values.netbird.namespace }}
  labels:
    app: {{ .Values.netbird.name }}
type: Opaque
stringData:
  management-url: {{ .Values.netbird.managementUrl | quote }}
  setup-key: {{ .Values.netbird.setupKey | quote }}
{{- end }}
