apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.uiPlugin.name }}-init-script-cm
  namespace: {{ .Values.uiPlugin.namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "5"
data:
  init.sh: {{ .Files.Get "scripts/init.sh" | quote }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.uiPlugin.name }}-init
  namespace: {{ .Values.uiPlugin.namespace }}
  labels:
    app: {{ .Values.uiPlugin.name }}
    {{- range $key, $value := .Values.daemonset.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "10"
spec:
  template:
    metadata:
      name: {{ .Values.uiPlugin.name }}-init
      labels:
        app: {{ .Values.uiPlugin.name }}
    spec:
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      restartPolicy: Never
      containers:
        - name: ui-plugin-init
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: UI_PLUGIN_NAME
              value: {{ .Values.uiPlugin.name | quote }}
            - name: UI_PLUGIN_NAMESPACE
              value: {{ .Values.uiPlugin.namespace | quote }}
            - name: UI_PLUGIN_ENDPOINT
              value: {{ .Values.uiPlugin.endpoint | quote }}
            - name: UI_PLUGIN_VERSION
              value: {{ .Values.uiPlugin.pluginVersion | quote }}
            - name: NO_CACHE
              value: {{ .Values.uiPlugin.noCache | quote }}
          command:
            - /bin/sh
            - /scripts/init.sh
          volumeMounts:
            - name: init-script
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: init-script
          configMap:
            name: {{ .Values.uiPlugin.name }}-init-script-cm
            defaultMode: 0755
---
