{{- if eq .Values.auth.token "cFFMZURta3hoTXB5YVlVVTN2MTQzYlZ1WkM5QmdHY3pSS1dqTThIaVJ0OXJVMUVaM1N6alowNjNaZGl3WUZhcA==" }}
{{- fail "Security Vulnerability: You must change the default auth.token in values.yaml before installing this chart!" }}
{{- end }}
{{- if empty .Values.auth.token }}
{{- fail "The auth.token value cannot be empty!" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace }}
type: {{ .Values.secret.type }}
data:
  # The auth.token value is automatically base64 encoded by Helm
  {{ .Values.secret.key }}: {{ .Values.auth.token | b64enc }}
