{{- if .Values.uiPlugin.enabled -}}
apiVersion: catalog.cattle.io/v1
kind: UIPlugin
metadata:
  name: {{ .Values.uiPlugin.name }}
  namespace: {{ .Values.uiPlugin.namespace }}
spec:
  pluginName: {{ .Values.uiPlugin.pluginName }}
  version: {{ .Values.uiPlugin.pluginVersion | quote }}
  endpoint: {{ .Values.uiPlugin.endpoint | quote }}
  noCache: {{ .Values.uiPlugin.noCache }}
{{- end }}