apiVersion: v2
name: node-shutdown
description: Secure node shutdown service for Harvester clusters
type: application
version: 1.3.1
appVersion: "1.3.1"
keywords:
  - harvester
  - shutdown
  - node
  - kubevirt
maintainers:
  - name: hvt-shutdown-addons
    url: https://github.com/zed378/hvt-shutdown-addons
