apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.secret.namespace }}
type: {{ .Values.secret.type }}
data:
  # The auth.token value is automatically base64 encoded by Helm
  {{ .Values.secret.key }}: {{ .Values.auth.token | b64enc }}
